collections:
    - name: "posts"
      label: "Posts"
      folder: "src/content/posts/en"
      create: true
      extension: "mdx"
      format: frontmatter
      fields:
          - { label: "Publication Date", name: "pubDate", widget: "datetime" }
          - label: "Author"
            name: "author"
            widget: "object"
            fields:
                - { label: "Name", name: "name", widget: "string" }
                - { label: "Link", name: "link", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - label: "Imagen"
            name: "image"
            widget: "image"
            required: true
            path: "src/assets/images"
            save_path: "@assets/images"
          - label: "Image Alt Text"
            name: "imageAlt"
            widget: "string"
          - { label: "Tags", name: "tags", widget: "list", allow_add: true, required: false }
          - { label: "Body", name: "body", widget: "markdown" }

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"

backend:
    name: git-gateway
    branch: main
