name: Auditoría con Unlighthouse (Manual)

on:
    workflow_dispatch:

jobs:
    audit:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout del código
              uses: actions/checkout@v3

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Cache de dependencias de Bun
              uses: actions/cache@v3
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - name: Instalar dependencias del sistema necesarias para Sharp
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libvips-dev

            - name: Instalar dependencias del proyecto
              run: bun install

            - name: Instalar herramientas globales (Netlify CLI y Unlighthouse)
              run: bun add -g netlify-cli @unlighthouse/cli

            - name: Ejecutar auditoría con Unlighthouse
              run: unlighthouse-ci
              continue-on-error: true # Para que el workflow no falle aunque la auditoría lo haga

            - name: Subir reporte a Netlify
              run: netlify deploy --dir=.unlighthouse --prod --message="📊 Reporte de auditoría desde GitHub Actions"
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
