name: Assertions and static report

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install project dependencies
              run: bun install

            - name: Install global tools (Netlify CLI and Unlighthouse only)
              run: bun add -g netlify-cli @unlighthouse/cli

            - name: Run Unlighthouse (audit report)
              run: unlighthouse-ci
              continue-on-error: true # Evita que falle todo el workflow si esto da error

            - name: Deploy Unlighthouse report to Netlify
              run: netlify deploy --dir=.unlighthouse --prod --message="New Release Deploy from GitHub Actions"
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
